### ISSUE TITLE
msbuild command for wapproj doesn't work locally via cli

### ISSUE THREAD

**Issue by bdrum** [microsoft/github-actions-for-desktop-apps#28]
Hi.

Thanks for the example. It's really helpful!

I would like to clarify some moment:
I study your ci.yml file and try to repeat all basics command locally on my machine.
So I've got a situation when I can build wapproject via visual studio, but it doesn't build via cli.

Environment:
~~~powershell
➜ dotnet --version
3.1.201
➜ dotnet msbuild
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core

➜ Get-ComputerInfo -Property @("OsVersion", "WindowsVersion", "CsSystemType")

OsVersion  WindowsVersion CsSystemType
---------  -------------- ------------
10.0.18363 1909           x64-based PC
~~~

As I've already mentioned I can build wapproject via visual studio (2019 community Version 16.5.3),
but

~~~powershell
➜ dotnet build
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

.wapproj(51,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.201\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that t
he expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.201\\Microsoft\DesktopBridge\\Microsoft.DesktopBridge.props" is correct, and that the file exists on disk.

Build FAILED.
~~~

Compiler complains on this row:

~~~xml
  <PropertyGroup>
    <WapProjPath Condition="'$(WapProjPath)'==''">$(MSBuildExtensionsPath)\Microsoft\DesktopBridge\</WapProjPath>
  </PropertyGroup>
  <Import Project="$(WapProjPath)\Microsoft.DesktopBridge.props" />
~~~

How I understood my .net core sdk doesn't have DesktopBridge.

With dotnet msbuild and all parameters like platform, UapAppxPackageBuildMode and so on the result will be the same.

Do you have any idea how to solve it and it possible in principle I mean pack win exe to appx via .net core sdk?

Thanks and good luck!

**Comment by bdrum** [comment]
Yes, restore option fixed it.

Many thanks!

**Comment by NSouth** [comment]
@bdrum, would you mind posting the CLI commands that worked for you? I am facing this same issue on my own project. I am restoring my WPF project before building as shown below.

`dotnet restore "F:\dev\mySolution.sln" /p:Configuration=Debug;RuntimeIdentifier="win-x64"
dotnet build "F:\dev\mySolution.sln" /p:Configuration=Debug;AppxBundle=Never;Platform=x64;UapAppxPackageBuildMode=SideloadOnly;RuntimeIdentifier="win-x64"`

Based on documentation `dotnet build` runs a restore implicitly, too. I am also declaring the runtime identifiers in my WPF project's .csproj:

`<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>`

However, I am still getting the error: 

> F:\dev\myWPF.Packaging.wapproj(56,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.201\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.201\\Microsoft\DesktopBridge\\Microsoft.DesktopBridge.props" is correct, and that the file exists on disk.

I would appreciate any help, as we need to be able to build via the dotnet core SDK. Thanks.

**Comment by bdrum** [comment]
@NSouth, yeah, sure:
~~~
➜ dotnet build .\GSIPackage.wapproj
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

GSIPackage.wapproj(51,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.202\Microsoft\DesktopBridge\Microsoft.DesktopBridge.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.202\\Microsoft\DesktopBridge\\Microsoft.DesktopBridge.props" is correct, and that the file exists on disk.

Build FAILED.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.23

➜ dotnet build .\GSIPackage.wapproj /t:Restore
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.30
~~~

**Comment by NSouth** [comment]
Thanks, but that looks like the build command that failed. For the sake of others, here's what is working for me in order to build in a Docker container:

### Make sure my WPF project and its references have RuntimeIdentifiers defined
`<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>` in each `.csproj`.

### Add dependencies to my docker image
For me, building only works when using the `msbuild.exe` that comes with Visual Studio, not when using `dotnet build` (the installed SDK). Therefore, I needed this on my container. I had to use a base image that already had .NET 4.8 because otherwise installing it requires a restart which is problematic when building the Docker image. Here's an abbreviated version of my dockerfile. The key components are

- From sdk:4.8 image
- Add VS2019 UWP build tools
- Add Windows 10 SDK

```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
 
SHELL ["powershell.exe", "-ExecutionPolicy", "Bypass", "-Command"]
 
RUN Install-PackageProvider NuGet -Force
RUN Import-PackageProvider NuGet -Force
 
# Install Chocolatey
RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
 
RUN choco install dotnetcore-sdk --version 3.1.201 -y
RUN choco install visualstudio2019-workload-universalbuildtools -y
RUN choco install windows-sdk-10-version-1903-all -y
```
### Restore the solution
In the container, the installed MSBuild.exe is found at 
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin
```
Using it, I run the restore operation (and seemingly don't need to pass the RuntimeIdentifier parameter). 
```
msbuild "F:\myPath\MySolution.sln" /t:Restore
```
For this, using `dotnet build` appears to also work:
```
dotnet build "F:\myPath\MySolution.sln" /t:Restore
```

### Build the solution
Finally, this is the build command that is working for me. I probably have some tweaks to make, but this works. My solution contains the WPF and WAP projects and I get the expected results in the AppxPackages folder of the WAP project.
```
msbuild "F:\myPath\MySolution.sln" /p:Configuration=Release;AppxBundle=Always;AppxBundlePlatforms="x86|x64";Platform=x64
```

**Comment by LanceMcCarthy** [comment]
@BenjaminMichaelis  @brmonaghan

I'll try some runs on a test branch to see if I can reproduce. Can you please share your workflow yaml?

**Comment by brmonaghan** [comment]
i got it fixed by removing the desktopbridge.
