### ISSUE TITLE
Difficulty creating a new repository

### ISSUE THREAD

**Issue by thiagosales007** [microsoft/github-actions-for-desktop-apps#39]
Good Morning
I would like a help please
My name and Thiago Sales thank you.
## How to solve?

# This message appears below
**This directory appears to be a Git repository. Would you like to add this repository instead?**

![image](https://user-images.githubusercontent.com/80003710/110951503-e7252f80-8323-11eb-8e4c-6d3905522921.png)

**Comment by LanceMcCarthy** [comment]
HI Thiago, 

That is the wrong form. It is for creating a **new** repository, you actually want to **clone** an existing repository.

Instead, go back to the home page of this repo and take the following steps

1. Click the **Code** button
2. Click Open in GitHub desktop
    ![image](https://user-images.githubusercontent.com/3520532/110953553-7ecf5180-8315-11eb-8df7-5e3a61168de4.png)
3. You browser will ask it is okay to open GitHub for Desktop, select OK.
4. Then complete the steps inside GitHub  for Desktop to clone the repo locally

**Comment by LanceMcCarthy** [comment]
Closing this as Unrelated

@thiagosales007  The problem you're having is due to being unfamiliar with GitHub for Desktop's UI or maybe git in general? If you have any further trouble, please reach out to me personally and I'd love to help out. (DM me [on Twitter](https://twitter.com/lancewmccarthy))
